repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.0
    hooks:
      - id: terraform_fmt
        files: ^infra/azure/terraform/.*
      - id: terraform_validate
        files: ^infra/azure/terraform/.*
      - id: terraform_tflint
        files: ^infra/azure/terraform/.*
        args:
          - "--args=--only=terraform_deprecated_interpolation"
          - "--args=--only=terraform_deprecated_index"
          - "--args=--only=terraform_unused_declarations"
          - "--args=--only=terraform_comment_syntax"
          - "--args=--only=terraform_documented_variables"
          - "--args=--only=terraform_typed_variables"
          - "--args=--only=terraform_module_pinned_source"
          # - '--args=--only=terraform_naming_convention'
          - "--args=--only=terraform_required_version"
          - "--args=--only=terraform_required_providers"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
        files: ^infra/azure/terraform/.*
      - id: end-of-file-fixer
        files: ^infra/azure/terraform/.*
